


### Requisição POST para criar um usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Rafael",
  "email": "Rafael.aaaa@gmail.com",
  "password": "Rafael123"
  
}

### Listar todos os usuarios
GET http://localhost:3000/users
Content-Type: application/json


### Editar usuario
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "Garbriel",
  "email": "gabriel.aaaa@gmail.com"
}

### Deletar usuario
DELETE http://localhost:3000/users/3


### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "Rafael.aaaa@gmail.com",
    "password": "Rafael123"
}

### User info
GET http://localhost:3000/userinfo
Authorization: Bearer {{token}}


### Cadastrar Categoria
POST http://localhost:3000/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bebidas"
}


### Listar todas as categorias
GET http://localhost:3000/category
Authorization: Bearer {{token}}

### Deletar categoria
DELETE http://localhost:3000/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 3
}



### Cadastrar Produto
POST http://localhost:3000/product
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="name"

Fanta Laranja 2L
--WebKitFormBoundary
Content-Disposition: form-data; name="description"

Refrigerante gelado
--WebKitFormBoundary
Content-Disposition: form-data; name="price"

5.90
--WebKitFormBoundary
Content-Disposition: form-data; name="category_id"

2
--WebKitFormBoundary
Content-Disposition: form-data; name="banner"; filename="FantaLaranja2.jpg"
Content-Type: image/jpeg

< ./imagem/FantaLaranja2.jpg
--WebKitFormBoundary--


### Pegar produtos Filtado por categoria
GET http://localhost:3000/product?category=2
Authorization: Bearer {{token}}


### Deletar produto
DELETE http://localhost:3000/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 13
}



### Criar Pedido/Order
POST http://localhost:3000/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "table": 15,
  "name": "João"
}

### Listar todas Orders
GET http://localhost:3000/order
Authorization: Bearer {{token}}


### Deletar um Order
DELETE http://localhost:3000/order?table=2
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary


### Adicionar um Item
POST http://localhost:3000/order/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "order_id": 13,
  "product_id": 9,
  "amount": 2 
}


### Pegar todos os items
GET http://localhost:3000/order/get
Authorization: Bearer {{token}}


### Remover um Item
DELETE http://localhost:3000/?id=11
Authorization: Bearer {{token}}


### Enviar pedido/draft: false
PUT http://localhost:3000/order/send
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 13 
}

### Pegar apenas Orders Pendentes draft e Status = false
GET http://localhost:3000/order/pending
Authorization: Bearer {{token}}


### Pegar os detalhes de uma order especifica
GET http://localhost:3000/order/details?order_id=12
Authorization: Bearer {{token}}


### Finalizar order/ status = True
PUT http://localhost:3000/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "order_id": 12 
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVzdGUiLCJlbWFpbCI6InRlc3RlQGVtYWlsLmNvbSIsInN1YmplY3QiOjIsImlhdCI6MTc0NzE2NTg0OSwiZXhwIjoxNzQ3MTY5NDQ5fQ.TgmiBUtjyCX8GLwm1R-KczQRZ8QJKh2ixg20P0Q3GtU
###
POST https://pizzaria-backend-production-bccd.up.railway.app/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@email.com",
  "password": "123456"
}


### Login
POST https://pizzaria-backend-production-bccd.up.railway.app/login
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "123456"

}

### Criar Pedido/Order
POST https://pizzaria-backend-production-bccd.up.railway.app/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "table": 15,
  "name": "João"
}


### Enviar pedido/draft: false
PUT https://pizzaria-backend-production-bccd.up.railway.app/order/send
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1
}


### Adicionar um Item
POST https://pizzaria-backend-production-bccd.up.railway.app/order/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "order_id": 2,
  "product_id": 1,
  "amount": 1
}


### Listar todas Orders
GET https://pizzaria-backend-production-bccd.up.railway.app/order
Authorization: Bearer {{token}}

### Deletar um Order
DELETE https://pizzaria-backend-production-bccd.up.railway.app/order/bulk
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ids": [33,40,41,42,43,44,45,46,47,48,49,50,51,52]
}


### Remover um Item
DELETE https://pizzaria-backend-production-bccd.up.railway.app/order/remove?id=11
Authorization: Bearer {{token}}

### Pegar todos os items
GET https://pizzaria-backend-production-bccd.up.railway.app/order/get
Authorization: Bearer {{token}}


### Pegar produtos Filtado por categoria
GET https://pizzaria-backend-production-bccd.up.railway.app/product?category=1
Authorization: Bearer {{token}}

### Listar categorias
GET https://pizzaria-backend-production-bccd.up.railway.app/category
Authorization: Bearer {{token}}


### Criar ingredient
POST https://pizzaria-backend-production-bccd.up.railway.app/ingredients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Calabresa",
  "unit": "g",
  "quantity": 10000
}

### Adicionar ao estoque
PATCH  https://pizzaria-backend-production-bccd.up.railway.app/ingredients/1/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 500
}

### remover do estoque
PATCH  https://pizzaria-backend-production-bccd.up.railway.app/ingredients/4/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 800
}

### Listar estoque
GET https://pizzaria-backend-production-bccd.up.railway.app/ingredients
Authorization: Bearer {{token}}

### Adicionar receita
POST https://pizzaria-backend-production-bccd.up.railway.app/recipes/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ingredients": [
    { "ingredient_id": 1, "quantity": 500 },
    { "ingredient_id": 2, "quantity": 25 },
    { "ingredient_id": 4, "quantity": 300 }
  ]
}

### Listar receita
GET https://pizzaria-backend-production-bccd.up.railway.app/recipes/2
Content-Type: application/json
Authorization: Bearer {{token}}